### ISSUE TITLE
训练后的效果

### ISSUE THREAD

**Issue by nealwon** [Triang-jyed-driung/RWKV-World-Finetune#1]
训练后效果如何？

我的语料格式是：
["text":"Question: aaaa\n\nAnswer: bbbb\n\nQuestion: cccc\n\nAnswer: dddd"]

训练下来问答和语料一点关系都没有。求指点

**Comment by mafamily2496** [comment]
同样，我效果也不行

**Comment by nealwon** [comment]
> 

我尝试用小模型进行全量微调，倒是回答的和语料有点关系，就是还是那种智障式的回答。

**Comment by YunzeSong** [comment]
是不是这个原因？
NOTE: the new greedy tokenizer (https://github.com/BlinkDL/ChatRWKV/blob/main/tokenizer/rwkv_tokenizer.py) will tokenize '\n\n' as one single token instead of ['\n','\n']

**Comment by nealwon** [comment]
能够按照语料答复，但是答非所问，用A的答案去答问题B。暂时不做微调了。
